language: node_js
node_js:
- 10
install:
- npm install
script:
- npm run cover
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: pim@witlox.io
  api_key:
    secure: bdFU2pVNQi0EvTojoWnjSZqlUEbb20TTGayes6K+IY9v9JLdZUAOJOEVYSWo/6mHOhJFc4j5HvHVyO1iRtxg0dWdraWaLzGJbuVplLkqlFkH3radKqF3THynCnF2k/LifQLytlkSm+/DQ35Iec0X+iB4OUZZi6aVA2mtUfpWiev29yoCYiuz1belLhhKk5YaWTDE4jOpAkmZQXb3ifFaK7vpVodZHO+rqmASquayMFg+GA0TQUOqp0fme7tWgTp0QFaHbqIqMpEklb9eYiiJv2XkSbRGrYOlap7KT1+6OPxnF25HtQ2UPitYJDv2eBcKhoq0hkVIcZ9LX1+tdIEicRlY5ucjon/rFnE2TTcFK/89uCPxHqGJIUDkLOMEqr3MBxhj6Ncny0fXZZkNnexwBmhO2RFWOmVNV+RSY2o6X/rWd8fjrEiWnB/AG0uQu17blm8AaPMpGh9SjbFaM9eoWLeBosfmlZ8euLsLHe+EwhF8t/cEw7s4ScOiTg49P5O3dXIZzb41z7M9us8iV6vKxVDGKObJT3v93IhuDFSuBwDKPpDKTeFTt7nZHAS+WCM6FlHRouxTCNQg6d3uBncJw2bt2l5lmfbNf6f5jQWlInSNowPzaXy1u07pVQln7BW3l5TeQa6SQj72PhD5G60KW3ZxyQ2/SyPweV+Sh+ex2oY=
  on:
    tags: true
    repo: witlox/acrion
